{% set name = "NgspiceSimServer" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NyanCAD/NgspiceSimServer/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7af0d52f1c42f72d8c49cae1fca8228886d4d1c80a1c81e3ce62afd5b6ae0beb

build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkgconfig
  host:
    - capnproto
    - ngspice-lib
    - libboost-devel
  run:
    - ngspice-lib

test:
  commands:
    - NgspiceSimServer --help

about:
  home: https://github.com/NyanCAD/SimServer
  license: MPL-2.0
  license_file: LICENSE
  summary: Cap'n Proto simulation server for Ngspice
  dev_url: https://github.com/NyanCAD/NgspiceSimServer

extra:
  recipe-maintainers:
    - pepijndevos
