{% set name = "NgspiceSimServer" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NyanCAD/NgspiceSimServer/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d7ca2708a05a5b634b9e1d83a9979bab513eb1d85490aec3254bff98d871e6a4

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkgconfig
  host:
    - capnproto
    - ngspice-lib
    - boost-cpp
  run:
    - ngspice-lib
    - boost-cpp
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - NgspiceSimServer --help

about:
  home: https://github.com/NyanCAD/SimServer
  license: MPL-2.0
  license_file: LICENSE
  summary: Cap'n Proto simulation server for Ngspice
  dev_url: https://github.com/NyanCAD/NgspiceSimServer

extra:
  recipe-maintainers:
    - pepijndevos
