{% set name = "NgspiceSimServer" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NyanCAD/NgspiceSimServer/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f9dcc5e1a9a473973c00474bf55ae6fa17636a09754b1558fc80000cc86f18d7

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkgconfig
  host:
    - capnproto
    - ngspice-lib
  run:
    - ngspice-lib
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - NgspiceSimServer --help

about:
  home: https://github.com/NyanCAD/SimServer
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Cap'n Proto simulation server for Ngspice
  dev_url: https://github.com/NyanCAD/NgspiceSimServer

extra:
  recipe-maintainers:
    - pepijndevos
