{% set name = "NgspiceSimServer" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NyanCAD/NgspiceSimServer/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2213080ddfaf656bc47146dd64241277c056b4f47f4bdace5001ff9f33d94d01

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkgconfig
  host:
    - capnproto
    - ngspice-lib
    - boost-cpp
  run:
    - ngspice-lib
    - boost-cpp
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - NgspiceSimServer --help

about:
  home: https://github.com/NyanCAD/SimServer
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: "Cap'n Proto simulation server for Ngspice"
  dev_url: https://github.com/NyanCAD/NgspiceSimServer

extra:
  recipe-maintainers:
    - pepijndevos
